

# API 서비스용 설정 (이미 배포했다면 선택사항)
[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api/Dockerfile"

[deploy]
startCommand = "node apps/api/dist/main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
